# -*- coding: utf-8 -*-
"""Data-Encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Kubj0s0kY16KKkLuaIm9Cbou_BBW6GH
"""

# Data encoding means converting the categogrical data into numeric data
# Machine learning model only understand the numeric data not a categoric data
# Gender - Male / Female => Male =0, Female = 1

# Types of Data encoding
# 1. Lable Encoding
# 2. One-Hot Encoding
# 3. Ordinal Encoding
# 4. Target Encoding

# Label Encoding: We do make use of label encoding when category have some order
# We have to avoid label encoding when the unordered category is there
# example size| small medium large small large

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('encoding_practice_500_records.csv')

df

df.info()

"""**Label Encoding**"""

from sklearn.preprocessing import LabelEncoder

# creating an object of it
le = LabelEncoder()

df['Department_Label'] = le.fit_transform(df['Department'])

df['Department'].unique()

df['Department_Label']

df.info()

"""**One Hot Encoding**"""

# get_dummies() is a pandas function that converts text categories into numbers (0 and 1).
df = pd.get_dummies(df,
               columns=['Gender'], drop_first=True)
# columns = which column to encode

df

# we will get only one column to avoid duplicates

df['City']

df['City'].unique()

df = pd.get_dummies(df, columns=['City'], drop_first=True)

df

df['Marital_Status'].unique()

df = pd.get_dummies(df, columns=['Marital_Status'], drop_first=True)

df

df.info()

"""**Ordinal Encoding**"""

# we make use of ordinal encoding when the order is mandetory

# we can do using map fucntion and also sklearn OrdinalEncoder but we will choose map function

df['Education_Level'].unique()
# here we do have 4 different education levels

education_order = {
    "School": 1,
    "College": 2,
    "Masters": 3,
    "PhD": 4
}

df["Education_Encoded"] = df["Education_Level"].map(education_order)

