# -*- coding: utf-8 -*-
"""Drug Concentration vs Absorption Rate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSolJmo8dZHq6xb1VX0pZ-Vf9RARHP7N

# **Title: Drug Concentration vs Absorption Rate**
"""

# We are building a model that learns how the body absorbs a drug at different concentration levels.

"""When a drug enters the body:

At low concentration → absorption increases slowly

At medium concentration → absorption increases faster

At high concentration → absorption slows or plateaus

This relationship is NOT a straight line.
That’s why we use polynomial regression.

**What are we building?**

We are building a mathematical model that:

Takes drug concentration as input
Predicts how fast the drug is absorbed
"""

# Drug concentration level means:
# How much drug is present in the body (or blood) at a given time

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('drug_concentration_absorption_polynomial_dirty_2000.csv')

df

import seaborn as sns

df.info()

sns.boxplot(x=df["Drug_Concentration_mg_L"])
plt.show()

sns.boxplot(x=df["Absorption_Rate_percent"])
plt.show()

df.info()

df['Drug_Concentration_mg_L']= df['Drug_Concentration_mg_L'].fillna(df['Drug_Concentration_mg_L'].mean())

df['Absorption_Rate_percent'] = df['Absorption_Rate_percent'].fillna(df['Absorption_Rate_percent'].median())

df.info()

X = df[["Drug_Concentration_mg_L"]]   # input
y = df["Absorption_Rate_percent"]     # output

# convert x into (x square)
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X)

# split into train and test

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_poly, y, test_size=0.2, random_state=42
)

# model building

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

# prediction

y_pred = model.predict(X_test)

# evaluation

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

new_concentration = [[25]]   # mg/L

new_concentration_poly = poly.transform(new_concentration)
prediction = model.predict(new_concentration_poly)

print("Predicted Absorption Rate:", prediction[0])

