# -*- coding: utf-8 -*-
"""regularization-L2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srptg0bpSgBIpi8fmjbw3pAPh2TLbTgI

**Title: Medical Insurance Dataset style project**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_csv('L2-medical-dataset.csv')

df.info()
df.describe()
df.isnull().sum()

# convert into catgories

df = pd.get_dummies(df, drop_first=True)

# Define target and feature

X = df.drop("charges", axis=1)
y = df["charges"]

# train test split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# feature scaling

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# building Ridge

ridge = Ridge(alpha=0.1)

# train
ridge.fit(X_train, y_train)

# Predictions

y_pred = ridge.predict(X_test)

# model evaluation

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)

# Residual analysis

residuals = y_test - y_pred

plt.figure(figsize=(6,4))
plt.scatter(y_pred, residuals)
plt.axhline(y=0, color='red')
plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.title("Residual Plot (Ridge)")
plt.show()

# Check Coefficients

coefficients = pd.Series(ridge.coef_, index=X.columns)
coefficients.sort_values().plot(kind='barh', figsize=(8,6))
plt.title("Feature Importance (Ridge)")
plt.show()

# alpha = 0.1 become less penalty
# alpha = 10 more penalty