# -*- coding: utf-8 -*-
"""Elastic-net.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cn0pzADEycWAFi_I_GGn-tbAxSaBoJ_T

**Title: Medical Insurance Dataset style project**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Elastic-net.csv')

df.info()

df.describe()

df.isnull().sum()

# convert categories into numeric

df = pd.get_dummies(df, drop_first=True)
df.head()

# Define feature and target

X = df.drop("charges", axis=1)
y = df["charges"]

# Train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build Elastic net model

from sklearn.linear_model import ElasticNet

elastic = ElasticNet(alpha=0.1, l1_ratio=0.5)
# it mean 50% of L1 & 50% of L2

elastic.fit(X_train, y_train)

# Make prediction

y_pred = elastic.predict(X_test)

# Model Evaluation

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)

# Residual Analysis

residuals = y_test - y_pred

plt.figure(figsize=(6,4))
plt.scatter(y_pred, residuals)
plt.axhline(y=0, color='red')
plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.title("Residual Plot (Elastic Net)")
plt.show()

