# -*- coding: utf-8 -*-
"""Random-Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9z836zIw_ZK7ttbkHhCZoMEBHPtTFL6

**Title: This dataset is originally from the National Institute of Diabetes and Digestive and Kidney Diseases. The objective of the dataset is to diagnostically predict whether or not a patient has diabetes, based on certain diagnostic measurements included in the dataset. Several constraints were placed on the selection of these instances from a larger database. **
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('diabetes-random-forest.csv')

df

df.info()

df['Outcome'].unique()

df.describe()

# here every data is in numeric format so we dont need to do data encoding

# splitting data into x and y

X = df.drop('Outcome', axis=1)
y = df['Outcome']

X

y

# train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape

X_test.shape

y_train.shape

# Scaling the data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# choosing and training the model

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

# Evaluate the model

from sklearn.metrics import accuracy_score, classification_report

y_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# here we are getting the accuracy of 72% it means its low

# Reason
# Slightly imbalanced
# Not perfectly seperable
# Default random forest parameter

# Lets check the class distribution

print(df['Outcome'].value_counts())

# so here we can see the distribution is not balanced so we need to balanced that

# check feature importance
import pandas as pd

feature_importance = pd.Series(rf.feature_importances_, index=X.columns)
print(feature_importance.sort_values(ascending=False))

# New patient data (must be 2D list)
new_patient = [[
    2,      # Pregnancies
    150,    # Glucose
    80,     # BloodPressure
    35,     # SkinThickness
    120,    # Insulin
    32.5,   # BMI
    0.5,    # DiabetesPedigreeFunction
    45      # Age
]]

# IMPORTANT: Scale new data (same scaler used earlier)
new_patient_scaled = scaler.transform(new_patient)

# Predict
prediction = rf.predict(new_patient_scaled)

if prediction[0] == 1:
    print("Patient is Diabetic")
else:
    print("Patient is Not Diabetic")

