# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-oyI3rGFYznfDaQMNA7BmaT2_uvOXXXm

**Title: Pima Diabetes Classification**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('naive-bayesdiabetes-svm.csv')
df.head()

df.info()
df.describe()
df.isnull().sum()

# check class balance

sns.countplot(x="Outcome", data=df)
plt.title("Class Distribution")
plt.show()

# Data cleaning
# Replace invalid zeros with median:

cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

for col in cols:
    df[col] = df[col].replace(0, np.nan)
    df[col].fillna(df[col].median(), inplace=True)

# Split into input and output

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

# Train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature Scaling & training the model

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Base line svm

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, roc_auc_score

svm_model = SVC(kernel='rbf', C=1, gamma='scale', probability=True)
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

print("Baseline SVM Accuracy:", accuracy_score(y_test, y_pred))

# confusion matrix

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt="d", cmap="Greens")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - SVM")
plt.show()

# classfication report

print(classification_report(y_test, y_pred))

# Getting the accuracy

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("SVM Accuracy:", accuracy)

# if we want accuracy in percent

print("SVM Accuracy: {:.2f}%".format(accuracy * 100))

# So here we had performed an SVM but the accuracy is 74% later on we will boosts it accuracy

# StandardScaler converts your data into a common scale so that all features have similar range.

