# -*- coding: utf-8 -*-
"""Drug-Classification-KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151HXaiEFtkHOKc7XzSKTk-TX5F07u4mx

**Project of KNN**

**Machine Learning classification model to predict the most suitable drug for a patient based on medical features such as Age, Sex, Blood Pressure, Cholesterol level, and Sodium-to-Potassium ratio.**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("drug200-knn.csv")

df.info()

df

df.info()

"""Seperate features and target"""

X = df.drop("Drug", axis=1)

y = df['Drug']

X

y

"""**Encoding categorical column**"""

X = pd.get_dummies(X, drop_first=True)

df['Drug'].unique()

"""**Label Encoder**"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = le.fit_transform(y)

"""**Feature Scaling**"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""**Train test split**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

X_train.shape

y_train.shape

y.shape

"""**Choosing the Model**"""

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
# created the object of knn

# here n_neighbours = 5 means when predicting look at nearest 5 points

"""**Training KNN Model**"""

knn.fit(X_train, y_train)

# Testing
y_pred = knn.predict(X_test)

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

# here we got the accuracy of 90%

# Lets check for new data

X.columns

new_data = [[29, 1, 2, 1, 17, 0]]  # Must match 6 features exactly
new_data = scaler.transform(new_data)

prediction = model.predict(new_data)
print("Predicted Drug:", prediction[0])

