# -*- coding: utf-8 -*-
"""Drug Manufacturing Cost vs Raw Material Cost-LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOdbqXzlGtsbMCZEjTZPALfxEshnKfde

# **Title: Drug Manufacturing Cost vs Raw Material Cost**

In pharmaceutical manufacturing, raw material cost (APIs, excipients, chemicals) is one of the largest contributors to total manufacturing cost.
This project studies and predicts:
How changes in raw material cost affect total drug manufacturing cost
"""

# Manufacturing_Cost (₹ / $ per batch or per unit)

"""Project working : Input & Output
Input (X): Raw Material Cost
Output (Y): Total Drug Manufacturing Cost
Both are continuous numeric values, which perfectly fits linear regression.

Explanation:


The project assumes a linear relationship, meaning: As raw material cost increases, total manufacturing cost increases proportionally.
"""

# Real-World Application Pharma companies can use this analysis to: Estimate manufacturing cost early in production planning
# Control raw material procurement Optimize supplier selection

import pandas as pd
import numpy as np

df = pd.read_csv('drug_manufacturing_cost_dataset.csv')

df.head()

df.isnull().sum()

df.info()

df.describe()

"""**Data Cleaning**"""

# handling missing values

df['Raw_Material_Cost'] = df['Raw_Material_Cost'].fillna(df['Raw_Material_Cost'].median())

df['Raw_Material_Cost'].isnull().sum()

df['Manufacturing_Cost'].isnull().sum()

df['Manufacturing_Cost'] = df['Manufacturing_Cost'].fillna(df['Manufacturing_Cost'].median())

df.duplicated().sum()

"""**Detecting outlier**"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure()
sns.boxplot(x=df['Manufacturing_Cost'])
plt.title("Outlier Detection – Manufacturing Cost")
plt.show()

# Middle box → normal data
# Lines → normal range
# Dots outside → outliers



# IQR Method (Most Used in Industry)

# IQR = Q3 − Q1

# Points far away from the straight-line trend → outliers

Q1 = df['Manufacturing_Cost'].quantile(0.25)
Q3 = df['Manufacturing_Cost'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Manufacturing_Cost'] < lower) |
              (df['Manufacturing_Cost'] > upper)]

outliers.head()

# again visualizing

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure()
sns.boxplot(x=df['Manufacturing_Cost'])
plt.title("Boxplot – Manufacturing Cost")
plt.show()

plt.figure()
plt.hist(df['Manufacturing_Cost'], bins=30)
plt.xlabel("Manufacturing Cost")
plt.ylabel("Frequency")
plt.title("Distribution of Manufacturing Cost")
plt.show()

"""Before building a simple linear regression model, you must confirm:
“Does a straight-line relationship exist between Raw Material Cost and Manufacturing Cost?”
"""

import matplotlib.pyplot as plt

plt.figure()
plt.scatter(df['Raw_Material_Cost'], df['Manufacturing_Cost'])
plt.xlabel("Raw Material Cost")
plt.ylabel("Manufacturing Cost")
plt.title("Linear Trend Check")
plt.show()



"""**Split into train and test**"""

# Define Input (X) and Output (y)

X = df[['Raw_Material_Cost']]   # must be 2D
y = df['Manufacturing_Cost']

# splitting into train and test

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Verify Split

print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

"""Model Training"""

# Import Linear Regression
from sklearn.linear_model import LinearRegression

# Create the Model
model = LinearRegression()

# Train the Model
model.fit(X_train, y_train)

# Get Model Parameters
print("Slope (m):", model.coef_[0])
print("Intercept (c):", model.intercept_)

"""This gives you the equation:
Manufacturing Cost = m × Raw Material Cost + c

Model Evaluation
"""

y_pred = model.predict(X_test)

# Mean Absolute Error (MAE)
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

# Mean Squared Error (MSE)
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

# R² Score (Most Important)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

"""**Predictions**"""

# Prepare New Input
# Single new value (must be 2D)
new_raw_material_cost = [[250]]  # value in thousands

# Predict Using Model

predicted_cost = model.predict(new_raw_material_cost)
print("Predicted Manufacturing Cost:", predicted_cost[0])

# Predict Multiple Values (Optional)
# Multiple new inputs
new_inputs = [[100], [200], [300], [400]]

predictions = model.predict(new_inputs)

for x, y in zip(new_inputs, predictions):
    print(f"Raw Material Cost: {x[0]} → Predicted Manufacturing Cost: {y:.2f}")

import matplotlib.pyplot as plt

plt.scatter(y_test, y_pred)
plt.xlabel("Actual Manufacturing Cost")
plt.ylabel("Predicted Manufacturing Cost")
plt.title("Actual vs Predicted")
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()])
plt.show()

residuals = y_test - y_pred
plt.scatter(X_test, residuals)
plt.axhline(0)
plt.xlabel("Raw Material Cost")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.show()

