# -*- coding: utf-8 -*-
"""regularization-L1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0BNpsXCFL7nyeDnvNG4l3-w5Qch2mxl

**Title: Predict medical insurance charges based on patient features using Lasso Regression.**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('l1-medical-dataset.csv')

df.info()

df.describe()

df.isnull().sum()

# Handling categogrical data

df = pd.get_dummies(df, drop_first=True)

df

df

# Splitting data into X & Y

X = df.drop("charges", axis=1)
y = df["charges"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.1) # alpha = lambda
lasso.fit(X_train, y_train)
y_predct = lasso.predict(X_test)

# higher alpha -> more shrinking
# lower alpha -> low shrinking

# Model Evaluation

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_predct)
mae

print("MAE:", mean_absolute_error(y_test, y_predct))
print("MSE:", mean_squared_error(y_test, y_predct))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_predct)))
print("R2:", r2_score(y_test, y_predct))

# Check Feature Selection (Important for L1)

# coefficients = pd.Series(lasso.coef_, index=X.columns) applying lasso for feature selection

coefficients = pd.Series(lasso.coef_, index=X.columns)
coefficients.sort_values().plot(kind='barh', figsize=(8,6))
plt.title("Feature Importance using Lasso")
plt.show()

# The feature does not contribute enough to reduce error compared to the penalty it adds.

# Some coefficients will be exactly 0. That means Lasso removed those features

import matplotlib.pyplot as plt
import numpy as np

# Step 1: Predictions
y_pred = lasso.predict(X_test)

# Step 2: Residuals
residuals = y_test - y_pred

# Step 3: Residual Plot
plt.figure(figsize=(6,4))
plt.scatter(y_pred, residuals)
plt.axhline(y=0, color='red')
plt.xlabel("Predicted Values")
plt.ylabel("Residuals (Actual - Predicted)")
plt.title("Residual Plot (Lasso)")
plt.show()

import matplotlib.pyplot as plt

# Step 1: Predictions
y_pred = lasso.predict(X_test)

# Step 2: Residuals
residuals = y_test - y_pred

# Step 3: Histogram
plt.figure(figsize=(6,4))
plt.hist(residuals, bins=30)
plt.xlabel("Residuals (Actual - Predicted)")
plt.ylabel("Frequency")
plt.title("Histogram of Residuals")
plt.show()

